services:
  postgres-db:
    image: postgres:latest
    container_name: onlybuns-postgres-db
    env_file:
      - database/.env
    command: ["postgres", "-c", "port=5433"]
    ports:
      - "5433:5433"

  redis-db:
    image: redis:latest
    container_name: onlybuns-redis-db
    ports:
      - "6379:6379"

  mongo-db:
    image: mongo:latest
    container_name: onlybuns-mongo-db
    env_file:
      - database/.env
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:latest
    container_name: onlybuns-rabbitmq
    ports:
      - "5672:5672"
      # - "15672:15672"

  vets:
    build:
      context: ./vets
      dockerfile: Dockerfile
    image: onlybuns-vets
    container_name: onlybuns-vets
    depends_on:
      - rabbitmq
    env_file:
      - vets/.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: onlybuns-backend
    container_name: onlybuns-backend
    depends_on:
      - postgres-db
      - mongo-db
      - redis-db
      - rabbitmq
    env_file:
      - backend/.env
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: onlybuns-frontend
    container_name: onlybuns-frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"